### ISSUE TITLE
pre trained model

### ISSUE THREAD

**Issue by ganeshmanikanta** [MrZilinXiao/VisionObjectDetection#2]
hello,

Thank you for your contribution. My question is do you have some thing which is pre trained model.I can download that model and use that model in the code provided to detect vehicle from drone videos
That could be great help
Thank you.

**Comment by MrZilinXiao** [comment]
Hello, 
There is a pretrained model for you to download, and actually it's just on the README page.

For my model training on VisDrone dataset: (BaiduNetdisk)https://pan.baidu.com/s/1vhSEPMckC7QogL1WdOjWVQ Code：ouvo
Feel free to give feedback! 
(It seems you're not a native English speaker.

**Comment by ganeshmanikanta** [comment]
Thank you for your quick reply. Yeah I am not native English speaker (I can see that in the message i posted). I was also a bit faster when i was writing this comment. I will try your pre-trained model and let you know. It would be easy for user if you can clearly mention where this pre-trained model need to be placed during execution of code.
Thanks.
