### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by jfncs** [MrZilinXiao/VisionObjectDetection#3]
Hi, can you share your pre-trained weights on gdrive? Thank you!

**Comment by MrZilinXiao** [comment]
Good idea! I would upload them tonight.

**Comment by MrZilinXiao** [comment]
> Hi, can you share your pre-trained weights on gdrive? Thank you!

https://drive.google.com/file/d/1UT_l0BkBTKZBT4wDqmFf4dU22fPz8g3K/view?usp=sharing
Hope it will help!

**Comment by Runkli** [comment]
Hi are the weights hosted on gdrive the max iterations?

**Comment by MrZilinXiao** [comment]
> Hi are the weights hosted on gdrive the max iterations?

It was trained on Google Cloud Platform for 60000+ iterations.
